"""empty message

Revision ID: a22d5cae70e9
Revises: 5db2f37b75ca
Create Date: 2023-07-27 20:04:42.399834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22d5cae70e9'
down_revision = '5db2f37b75ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('date_publish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_publish', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
