"""empty message

Revision ID: b29c75bc4b74
Revises: a22d5cae70e9
Create Date: 2023-07-27 20:13:07.222811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29c75bc4b74'
down_revision = 'a22d5cae70e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('date_publish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_publish', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
