"""empty message

Revision ID: cc2b2a8efebc
Revises: 33411bdd46b7
Create Date: 2023-07-27 16:53:26.518782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2b2a8efebc'
down_revision = '33411bdd46b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('date_publish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_publish', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
